dist: xenial
language: rust
sudo: required

env:
  global:
    - CRATE_NAME=mavlink2rest

matrix:
  include:
    - os: linux
      dist: xenial
      env:
        - TARGET=armv7-unknown-linux-musleabihf
      addons:
        apt:
          packages:
            - libudev-dev

    - os: linux
      dist: xenial
      env:
        - TARGET=x86_64-unknown-linux-musl
      addons:
        apt:
          packages:
            - libudev-dev

    - os: osx
      compiler: clang
      env:
        - TARGET=x86_64-apple-darwin

before_install:
  - set -e
  - rustup self update

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt install -y $LINKER; fi
  - rustup install stable
  - rustup default stable
  - cargo install cross
  - cross build --verbose --release --target=$TARGET
  - cp target/$TARGET/release/$CRATE_NAME $CRATE_NAME-$TARGET

before_deploy:
  - git config --local user.name "Patrick Jos√© Pereira"
  - git config --local user.email "patrickelectric@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-continuous}
  - git tag $TRAVIS_TAG --force

deploy:
  provider: releases
  branch: master
  api_key:
    secure: a4UjRLJV8oreTDEqMbudUYyChSRMgD7v+U3SvAh/q+HiPhG1q1KzdUMQBcINgl453xEbA+8mf7jxlZW9falRwjy/idIfeaPS+il3nPt4c04HzvOdAM7Qbx6pmexwn5qwskSFPrOiIEQEadaer6axtA6F3bMkqszxDwQ093f0JtZ75/PLzuatRmmpH3KGIbRKM+CIj8C1renj8M2LMLfdhbVY8yvT3xYVofj/7Cb6ZwmvtM9vdLr7UGIeOh3x9V8nhJxd6vaA+Hnf+O5+YREaxGPELcUJygKl0dt4QbhyLbaPKQtyo2BjBSQ1qxVSQ0S8Q1aqBKY6CGYPOT4i+KSwEZyIziOeOjPwOBFgcfPShPVj/2BYep8HFhzSJ0M8wc6XqpeOAxefxpaJzO2n+GG0JgsJlkrIH0JOLjbaKqT3gS0fwtp2c+jaYUSrlljQTsdTY5inDLPypSyjll6F0K2v/WzPY+IJLXp+yAlNrrrYV+psU8CDcjCla+ulW/qKiJ1NatJDRtlLxDDTUEo7aXsT+xEC26ozk7R7uolfSyUVHURtg0cIRcJDVZuJSNS2Y7/FmeVnK/wuqOqKmfLtVn0MWebyc2HYeMx/oeUrW64Vgxo9V6gCgtwM53z/WKwkkHtEdDRx/CQHVEVkrCupF91RyHQHl+9otzd+52qiAF141eY=
  file_glob: true
  overwrite: true
  skip_cleanup: true
  file: $CRATE_NAME-$TARGET
  on:
    all_branches: true
