[package]
name = "mavlink2rest"
version = "0.7.1"
description = "A simple REST API for MAVLink"
readme = "README.md"
license = "MIT"
authors = ["Patrick Jos√© Pereira <patrickelectric@gmail.com>"]
edition = "2018"
path = "build.rs"

documentation = "https://github.com/patrickelectric/mavlink2rest"
homepage = "https://github.com/patrickelectric/mavlink2rest"
repository = "https://github.com/patrickelectric/mavlink2rest"

[[bin]]
bench = false
path = "src/main.rs"
name = "mavlink2rest"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.1"
actix-web = "1.0.8"
chrono = { version = "0.4", features = ["serde"] }
clap = "2.31.2"
mavlink = "0.8.2"
serde = "1.0.101"
serde_json = "1.0.41"
serde_derive = "1.0.104"
vergen = "3"

[build-dependencies]
vergen = "3"
